// Generated by supabase -- do not edit
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      access_token: {
        Row: {
          access_token: string
          code: string | null
          created_date: string
          platform_account_id: number | null
          request_id: string
        }
        Insert: {
          access_token: string
          code?: string | null
          created_date?: string
          platform_account_id?: number | null
          request_id: string
        }
        Update: {
          access_token?: string
          code?: string | null
          created_date?: string
          platform_account_id?: number | null
          request_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "access_token_platform_account_id_fkey"
            columns: ["platform_account_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "access_token_platform_account_id_fkey"
            columns: ["platform_account_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
        ]
      }
      AgentIdentifier: {
        Row: {
          account_id: number
          identifier_type: Database["public"]["Enums"]["AgentIdentifierType"]
          trusted: boolean
          value: string
        }
        Insert: {
          account_id: number
          identifier_type: Database["public"]["Enums"]["AgentIdentifierType"]
          trusted?: boolean
          value: string
        }
        Update: {
          account_id?: number
          identifier_type?: Database["public"]["Enums"]["AgentIdentifierType"]
          trusted?: boolean
          value?: string
        }
        Relationships: [
          {
            foreignKeyName: "AgentIdentifier_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "AgentIdentifier_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
        ]
      }
      Concept: {
        Row: {
          arity: number | null
          author_id: number | null
          created: string
          description: string | null
          epistemic_status: Database["public"]["Enums"]["EpistemicStatus"]
          id: number
          is_schema: boolean
          last_modified: string
          literal_content: Json
          name: string
          reference_content: Json
          refs: number[]
          schema_id: number | null
          source_local_id: string | null
          space_id: number
        }
        Insert: {
          arity?: number | null
          author_id?: number | null
          created: string
          description?: string | null
          epistemic_status?: Database["public"]["Enums"]["EpistemicStatus"]
          id?: number
          is_schema?: boolean
          last_modified: string
          literal_content?: Json
          name: string
          reference_content?: Json
          refs?: number[]
          schema_id?: number | null
          source_local_id?: string | null
          space_id: number
        }
        Update: {
          arity?: number | null
          author_id?: number | null
          created?: string
          description?: string | null
          epistemic_status?: Database["public"]["Enums"]["EpistemicStatus"]
          id?: number
          is_schema?: boolean
          last_modified?: string
          literal_content?: Json
          name?: string
          reference_content?: Json
          refs?: number[]
          schema_id?: number | null
          source_local_id?: string | null
          space_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "Concept_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "Concept"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "my_concepts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      concept_contributors: {
        Row: {
          concept_id: number
          contributor_id: number
        }
        Insert: {
          concept_id: number
          contributor_id: number
        }
        Update: {
          concept_id?: number
          contributor_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "concept_contributors_concept_id_fkey"
            columns: ["concept_id"]
            isOneToOne: false
            referencedRelation: "Concept"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "concept_contributors_concept_id_fkey"
            columns: ["concept_id"]
            isOneToOne: false
            referencedRelation: "my_concepts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "concept_contributors_contributor_id_fkey"
            columns: ["contributor_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "concept_contributors_contributor_id_fkey"
            columns: ["contributor_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
        ]
      }
      Content: {
        Row: {
          author_id: number | null
          created: string
          creator_id: number | null
          document_id: number
          id: number
          last_modified: string
          metadata: Json
          part_of_id: number | null
          scale: Database["public"]["Enums"]["Scale"]
          source_local_id: string | null
          space_id: number | null
          text: string
          variant: Database["public"]["Enums"]["ContentVariant"]
        }
        Insert: {
          author_id?: number | null
          created: string
          creator_id?: number | null
          document_id: number
          id?: number
          last_modified: string
          metadata?: Json
          part_of_id?: number | null
          scale: Database["public"]["Enums"]["Scale"]
          source_local_id?: string | null
          space_id?: number | null
          text: string
          variant?: Database["public"]["Enums"]["ContentVariant"]
        }
        Update: {
          author_id?: number | null
          created?: string
          creator_id?: number | null
          document_id?: number
          id?: number
          last_modified?: string
          metadata?: Json
          part_of_id?: number | null
          scale?: Database["public"]["Enums"]["Scale"]
          source_local_id?: string | null
          space_id?: number | null
          text?: string
          variant?: Database["public"]["Enums"]["ContentVariant"]
        }
        Relationships: [
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "Document"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "my_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "Content"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      content_contributors: {
        Row: {
          content_id: number
          contributor_id: number
        }
        Insert: {
          content_id: number
          contributor_id: number
        }
        Update: {
          content_id?: number
          contributor_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "content_contributors_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "Content"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_contributors_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "my_contents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_contributors_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_contributors_contributor_id_fkey"
            columns: ["contributor_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_contributors_contributor_id_fkey"
            columns: ["contributor_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
        ]
      }
      ContentEmbedding_openai_text_embedding_3_small_1536: {
        Row: {
          model: Database["public"]["Enums"]["EmbeddingName"]
          obsolete: boolean | null
          target_id: number
          vector: string
        }
        Insert: {
          model?: Database["public"]["Enums"]["EmbeddingName"]
          obsolete?: boolean | null
          target_id: number
          vector: string
        }
        Update: {
          model?: Database["public"]["Enums"]["EmbeddingName"]
          obsolete?: boolean | null
          target_id?: number
          vector?: string
        }
        Relationships: [
          {
            foreignKeyName: "ContentEmbedding_openai_text_embedding_3_small_1_target_id_fkey"
            columns: ["target_id"]
            isOneToOne: true
            referencedRelation: "Content"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ContentEmbedding_openai_text_embedding_3_small_1_target_id_fkey"
            columns: ["target_id"]
            isOneToOne: true
            referencedRelation: "my_contents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ContentEmbedding_openai_text_embedding_3_small_1_target_id_fkey"
            columns: ["target_id"]
            isOneToOne: true
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["id"]
          },
        ]
      }
      Document: {
        Row: {
          author_id: number
          contents: unknown
          created: string
          id: number
          last_modified: string
          metadata: Json
          source_local_id: string | null
          space_id: number | null
          url: string | null
        }
        Insert: {
          author_id: number
          contents?: unknown
          created: string
          id?: number
          last_modified: string
          metadata?: Json
          source_local_id?: string | null
          space_id?: number | null
          url?: string | null
        }
        Update: {
          author_id?: number
          contents?: unknown
          created?: string
          id?: number
          last_modified?: string
          metadata?: Json
          source_local_id?: string | null
          space_id?: number | null
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "Document_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      file_gc: {
        Row: {
          filehash: string
        }
        Insert: {
          filehash: string
        }
        Update: {
          filehash?: string
        }
        Relationships: []
      }
      FileReference: {
        Row: {
          created: string
          filehash: string
          filepath: string
          last_modified: string
          source_local_id: string
          space_id: number
          variant: Database["public"]["Enums"]["ContentVariant"] | null
        }
        Insert: {
          created: string
          filehash: string
          filepath: string
          last_modified: string
          source_local_id: string
          space_id: number
          variant?: Database["public"]["Enums"]["ContentVariant"] | null
        }
        Update: {
          created?: string
          filehash?: string
          filepath?: string
          last_modified?: string
          source_local_id?: string
          space_id?: number
          variant?: Database["public"]["Enums"]["ContentVariant"] | null
        }
        Relationships: [
          {
            foreignKeyName: "FileReference_content_fkey"
            columns: ["space_id", "source_local_id", "variant"]
            isOneToOne: false
            referencedRelation: "Content"
            referencedColumns: ["space_id", "source_local_id", "variant"]
          },
          {
            foreignKeyName: "FileReference_content_fkey"
            columns: ["space_id", "source_local_id", "variant"]
            isOneToOne: false
            referencedRelation: "my_contents"
            referencedColumns: ["space_id", "source_local_id", "variant"]
          },
          {
            foreignKeyName: "FileReference_content_fkey"
            columns: ["space_id", "source_local_id", "variant"]
            isOneToOne: false
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["space_id", "source_local_id", "variant"]
          },
        ]
      }
      group_membership: {
        Row: {
          admin: boolean | null
          group_id: string
          member_id: string
        }
        Insert: {
          admin?: boolean | null
          group_id: string
          member_id: string
        }
        Update: {
          admin?: boolean | null
          group_id?: string
          member_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_membership_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_membership_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      LocalAccess: {
        Row: {
          account_id: number
          space_id: number
        }
        Insert: {
          account_id: number
          space_id: number
        }
        Update: {
          account_id?: number
          space_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "LocalAccess_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "LocalAccess_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "LocalAccess_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "LocalAccess_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      PlatformAccount: {
        Row: {
          account_local_id: string
          active: boolean
          agent_type: Database["public"]["Enums"]["AgentType"]
          dg_account: string | null
          id: number
          metadata: Json
          name: string
          platform: Database["public"]["Enums"]["Platform"]
          write_permission: boolean
        }
        Insert: {
          account_local_id: string
          active?: boolean
          agent_type?: Database["public"]["Enums"]["AgentType"]
          dg_account?: string | null
          id?: number
          metadata?: Json
          name: string
          platform: Database["public"]["Enums"]["Platform"]
          write_permission?: boolean
        }
        Update: {
          account_local_id?: string
          active?: boolean
          agent_type?: Database["public"]["Enums"]["AgentType"]
          dg_account?: string | null
          id?: number
          metadata?: Json
          name?: string
          platform?: Database["public"]["Enums"]["Platform"]
          write_permission?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "PlatformAccount_dg_account_fkey"
            columns: ["dg_account"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      ResourceAccess: {
        Row: {
          account_uid: string
          source_local_id: string
          space_id: number
        }
        Insert: {
          account_uid: string
          source_local_id: string
          space_id: number
        }
        Update: {
          account_uid?: string
          source_local_id?: string
          space_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "ResourceAccess_account_uid_fkey"
            columns: ["account_uid"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      secret_token: {
        Row: {
          creator: string
          expiry_date: string | null
          id: string
          one_time_use: boolean | null
          payload: Json
        }
        Insert: {
          creator?: string
          expiry_date?: string | null
          id?: string
          one_time_use?: boolean | null
          payload: Json
        }
        Update: {
          creator?: string
          expiry_date?: string | null
          id?: string
          one_time_use?: boolean | null
          payload?: Json
        }
        Relationships: []
      }
      Space: {
        Row: {
          id: number
          name: string
          platform: Database["public"]["Enums"]["Platform"]
          url: string
        }
        Insert: {
          id?: number
          name: string
          platform: Database["public"]["Enums"]["Platform"]
          url: string
        }
        Update: {
          id?: number
          name?: string
          platform?: Database["public"]["Enums"]["Platform"]
          url?: string
        }
        Relationships: []
      }
      SpaceAccess: {
        Row: {
          account_uid: string
          permissions: Database["public"]["Enums"]["SpaceAccessPermissions"]
          space_id: number
        }
        Insert: {
          account_uid: string
          permissions: Database["public"]["Enums"]["SpaceAccessPermissions"]
          space_id: number
        }
        Update: {
          account_uid?: string
          permissions?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          space_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "SpaceAccess_account_uid_fkey"
            columns: ["account_uid"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "SpaceAccess_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "SpaceAccess_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      sync_info: {
        Row: {
          failure_count: number | null
          id: number
          last_success_start: string | null
          last_task_end: string | null
          last_task_start: string
          status: Database["public"]["Enums"]["task_status"] | null
          sync_function: string | null
          sync_target: number | null
          target_type: Database["public"]["Enums"]["EntityType"]
          task_times_out_at: string | null
          worker: string
        }
        Insert: {
          failure_count?: number | null
          id?: number
          last_success_start?: string | null
          last_task_end?: string | null
          last_task_start: string
          status?: Database["public"]["Enums"]["task_status"] | null
          sync_function?: string | null
          sync_target?: number | null
          target_type?: Database["public"]["Enums"]["EntityType"]
          task_times_out_at?: string | null
          worker: string
        }
        Update: {
          failure_count?: number | null
          id?: number
          last_success_start?: string | null
          last_task_end?: string | null
          last_task_start?: string
          status?: Database["public"]["Enums"]["task_status"] | null
          sync_function?: string | null
          sync_target?: number | null
          target_type?: Database["public"]["Enums"]["EntityType"]
          task_times_out_at?: string | null
          worker?: string
        }
        Relationships: []
      }
    }
    Views: {
      my_accounts: {
        Row: {
          account_local_id: string | null
          active: boolean | null
          agent_type: Database["public"]["Enums"]["AgentType"] | null
          dg_account: string | null
          id: number | null
          metadata: Json | null
          name: string | null
          platform: Database["public"]["Enums"]["Platform"] | null
          write_permission: boolean | null
        }
        Insert: {
          account_local_id?: string | null
          active?: boolean | null
          agent_type?: Database["public"]["Enums"]["AgentType"] | null
          dg_account?: string | null
          id?: number | null
          metadata?: Json | null
          name?: string | null
          platform?: Database["public"]["Enums"]["Platform"] | null
          write_permission?: boolean | null
        }
        Update: {
          account_local_id?: string | null
          active?: boolean | null
          agent_type?: Database["public"]["Enums"]["AgentType"] | null
          dg_account?: string | null
          id?: number | null
          metadata?: Json | null
          name?: string | null
          platform?: Database["public"]["Enums"]["Platform"] | null
          write_permission?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "PlatformAccount_dg_account_fkey"
            columns: ["dg_account"]
            isOneToOne: false
            referencedRelation: "my_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      my_concepts: {
        Row: {
          arity: number | null
          author_id: number | null
          created: string | null
          description: string | null
          epistemic_status:
            | Database["public"]["Enums"]["EpistemicStatus"]
            | null
          id: number | null
          is_schema: boolean | null
          last_modified: string | null
          literal_content: Json | null
          name: string | null
          reference_content: Json | null
          refs: number[] | null
          schema_id: number | null
          source_local_id: string | null
          space_id: number | null
        }
        Relationships: [
          {
            foreignKeyName: "Concept_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "Concept"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "my_concepts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Concept_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      my_contents: {
        Row: {
          author_id: number | null
          created: string | null
          creator_id: number | null
          document_id: number | null
          id: number | null
          last_modified: string | null
          metadata: Json | null
          part_of_id: number | null
          scale: Database["public"]["Enums"]["Scale"] | null
          source_local_id: string | null
          space_id: number | null
          text: string | null
          variant: Database["public"]["Enums"]["ContentVariant"] | null
        }
        Relationships: [
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "Document"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "my_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "Content"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      my_contents_with_embedding_openai_text_embedding_3_small_1536: {
        Row: {
          author_id: number | null
          created: string | null
          creator_id: number | null
          document_id: number | null
          id: number | null
          last_modified: string | null
          metadata: Json | null
          model: Database["public"]["Enums"]["EmbeddingName"] | null
          part_of_id: number | null
          scale: Database["public"]["Enums"]["Scale"] | null
          source_local_id: string | null
          space_id: number | null
          text: string | null
          variant: Database["public"]["Enums"]["ContentVariant"] | null
          vector: string | null
        }
        Relationships: [
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "Document"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "my_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "Content"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_part_of_id_fkey"
            columns: ["part_of_id"]
            isOneToOne: false
            referencedRelation: "my_contents_with_embedding_openai_text_embedding_3_small_1536"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Content_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      my_documents: {
        Row: {
          author_id: number | null
          contents: unknown
          created: string | null
          id: number | null
          last_modified: string | null
          metadata: Json | null
          source_local_id: string | null
          space_id: number | null
          url: string | null
        }
        Relationships: [
          {
            foreignKeyName: "Document_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "my_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "PlatformAccount"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "my_spaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Document_space_id_fkey"
            columns: ["space_id"]
            isOneToOne: false
            referencedRelation: "Space"
            referencedColumns: ["id"]
          },
        ]
      }
      my_file_references: {
        Row: {
          created: string | null
          filehash: string | null
          filepath: string | null
          last_modified: string | null
          source_local_id: string | null
          space_id: number | null
        }
        Relationships: []
      }
      my_groups: {
        Row: {
          id: string | null
          name: string | null
        }
        Relationships: []
      }
      my_spaces: {
        Row: {
          id: number | null
          name: string | null
          platform: Database["public"]["Enums"]["Platform"] | null
          url: string | null
        }
        Insert: {
          id?: number | null
          name?: string | null
          platform?: Database["public"]["Enums"]["Platform"] | null
          url?: string | null
        }
        Update: {
          id?: number | null
          name?: string | null
          platform?: Database["public"]["Enums"]["Platform"] | null
          url?: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      _local_concept_to_db_concept: {
        Args: {
          data: Database["public"]["CompositeTypes"]["concept_local_input"]
        }
        Returns: {
          arity: number | null
          author_id: number | null
          created: string
          description: string | null
          epistemic_status: Database["public"]["Enums"]["EpistemicStatus"]
          id: number
          is_schema: boolean
          last_modified: string
          literal_content: Json
          name: string
          reference_content: Json
          refs: number[]
          schema_id: number | null
          source_local_id: string | null
          space_id: number
        }
        SetofOptions: {
          from: "concept_local_input"
          to: "Concept"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      _local_content_to_db_content: {
        Args: {
          data: Database["public"]["CompositeTypes"]["content_local_input"]
        }
        Returns: {
          author_id: number | null
          created: string
          creator_id: number | null
          document_id: number
          id: number
          last_modified: string
          metadata: Json
          part_of_id: number | null
          scale: Database["public"]["Enums"]["Scale"]
          source_local_id: string | null
          space_id: number | null
          text: string
          variant: Database["public"]["Enums"]["ContentVariant"]
        }
        SetofOptions: {
          from: "content_local_input"
          to: "Content"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      _local_document_to_db_document: {
        Args: {
          data: Database["public"]["CompositeTypes"]["document_local_input"]
        }
        Returns: {
          author_id: number
          contents: unknown
          created: string
          id: number
          last_modified: string
          metadata: Json
          source_local_id: string | null
          space_id: number | null
          url: string | null
        }
        SetofOptions: {
          from: "document_local_input"
          to: "Document"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      account_in_shared_space: {
        Args: {
          access_level?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          p_account_id: number
        }
        Returns: boolean
      }
      author_of_concept: {
        Args: { concept: Database["public"]["Views"]["my_concepts"]["Row"] }
        Returns: {
          account_local_id: string | null
          active: boolean | null
          agent_type: Database["public"]["Enums"]["AgentType"] | null
          dg_account: string | null
          id: number | null
          metadata: Json | null
          name: string | null
          platform: Database["public"]["Enums"]["Platform"] | null
          write_permission: boolean | null
        }
        SetofOptions: {
          from: "my_concepts"
          to: "my_accounts"
          isOneToOne: true
          isSetofReturn: true
        }
      }
      author_of_content: {
        Args: { content: Database["public"]["Views"]["my_contents"]["Row"] }
        Returns: {
          account_local_id: string | null
          active: boolean | null
          agent_type: Database["public"]["Enums"]["AgentType"] | null
          dg_account: string | null
          id: number | null
          metadata: Json | null
          name: string | null
          platform: Database["public"]["Enums"]["Platform"] | null
          write_permission: boolean | null
        }
        SetofOptions: {
          from: "my_contents"
          to: "my_accounts"
          isOneToOne: true
          isSetofReturn: true
        }
      }
      can_access_account: { Args: { account_uid: string }; Returns: boolean }
      can_view_content: { Args: { content_id: number }; Returns: boolean }
      can_view_specific_resource: {
        Args: { source_local_id_: string; space_id_: number }
        Returns: boolean
      }
      compute_arity_local: {
        Args: { lit_content: Json; schema_id: number }
        Returns: number
      }
      concept_in_relations:
        | {
            Args: { concept: Database["public"]["Tables"]["Concept"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.concept_in_relations(concept => Concept), public.concept_in_relations(concept => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: '"Concept"'
              to: "Concept"
              isOneToOne: false
              isSetofReturn: true
            }
          }
        | {
            Args: { concept: Database["public"]["Views"]["my_concepts"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.concept_in_relations(concept => Concept), public.concept_in_relations(concept => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: "my_concepts"
              to: "my_concepts"
              isOneToOne: false
              isSetofReturn: true
            }
          }
      concept_in_space: {
        Args: {
          access_level?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          concept_id: number
        }
        Returns: boolean
      }
      concepts_of_relation:
        | {
            Args: { relation: Database["public"]["Tables"]["Concept"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.concepts_of_relation(relation => Concept), public.concepts_of_relation(relation => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: '"Concept"'
              to: "Concept"
              isOneToOne: false
              isSetofReturn: true
            }
          }
        | {
            Args: {
              relation: Database["public"]["Views"]["my_concepts"]["Row"]
            }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.concepts_of_relation(relation => Concept), public.concepts_of_relation(relation => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: "my_concepts"
              to: "my_concepts"
              isOneToOne: false
              isSetofReturn: true
            }
          }
      content_in_space: {
        Args: {
          access_level?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          content_id: number
        }
        Returns: boolean
      }
      content_of_concept: {
        Args: { concept: Database["public"]["Views"]["my_concepts"]["Row"] }
        Returns: {
          author_id: number | null
          created: string | null
          creator_id: number | null
          document_id: number | null
          id: number | null
          last_modified: string | null
          metadata: Json | null
          part_of_id: number | null
          scale: Database["public"]["Enums"]["Scale"] | null
          source_local_id: string | null
          space_id: number | null
          text: string | null
          variant: Database["public"]["Enums"]["ContentVariant"] | null
        }
        SetofOptions: {
          from: "my_concepts"
          to: "my_contents"
          isOneToOne: true
          isSetofReturn: true
        }
      }
      create_account_in_space: {
        Args: {
          account_local_id_: string
          email_?: string
          email_trusted?: boolean
          name_: string
          permissions_?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          space_id_: number
        }
        Returns: number
      }
      create_secret_token: {
        Args: {
          expiry_interval?: string
          v_one_time_use?: boolean
          v_payload: Json
        }
        Returns: string
      }
      document_in_space: { Args: { document_id: number }; Returns: boolean }
      document_of_content: {
        Args: { content: Database["public"]["Views"]["my_contents"]["Row"] }
        Returns: {
          author_id: number | null
          contents: unknown
          created: string | null
          id: number | null
          last_modified: string | null
          metadata: Json | null
          source_local_id: string | null
          space_id: number | null
          url: string | null
        }
        SetofOptions: {
          from: "my_contents"
          to: "my_documents"
          isOneToOne: true
          isSetofReturn: true
        }
      }
      end_sync_task: {
        Args: {
          s_function: string
          s_started_at?: string
          s_status: Database["public"]["Enums"]["task_status"]
          s_target: number
          s_worker: string
        }
        Returns: undefined
      }
      extract_references: { Args: { refs: Json }; Returns: number[] }
      file_access: { Args: { hashvalue: string }; Returns: boolean }
      file_exists: { Args: { hashvalue: string }; Returns: boolean }
      generic_entity_access: {
        Args: {
          target_id: number
          target_type: Database["public"]["Enums"]["EntityType"]
        }
        Returns: boolean
      }
      get_secret_token: { Args: { token: string }; Returns: Json }
      get_space_anonymous_email: {
        Args: {
          platform: Database["public"]["Enums"]["Platform"]
          space_id: number
        }
        Returns: string
      }
      group_exists: { Args: { group_id_: string }; Returns: boolean }
      group_members: {
        Args: { p_group_id: string }
        Returns: Database["public"]["CompositeTypes"]["group_member_info"][]
        SetofOptions: {
          from: "*"
          to: "group_member_info"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      in_group: { Args: { group_id_: string }; Returns: boolean }
      in_space: {
        Args: {
          access_level?: Database["public"]["Enums"]["SpaceAccessPermissions"]
          space_id: number
        }
        Returns: boolean
      }
      instances_of_schema:
        | {
            Args: { schema: Database["public"]["Tables"]["Concept"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.instances_of_schema(schema => Concept), public.instances_of_schema(schema => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: '"Concept"'
              to: "Concept"
              isOneToOne: false
              isSetofReturn: true
            }
          }
        | {
            Args: { schema: Database["public"]["Views"]["my_concepts"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.instances_of_schema(schema => Concept), public.instances_of_schema(schema => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"[]
            SetofOptions: {
              from: "my_concepts"
              to: "my_concepts"
              isOneToOne: false
              isSetofReturn: true
            }
          }
      is_group_admin: { Args: { group_id_: string }; Returns: boolean }
      is_last_local_reference: {
        Args: { source_local_id_: string; space_id_: number }
        Returns: boolean
      }
      is_my_account: { Args: { account_id: number }; Returns: boolean }
      match_content_embeddings: {
        Args: {
          current_document_id?: number
          match_count: number
          match_threshold: number
          query_embedding: string
        }
        Returns: {
          content_id: number
          roam_uid: string
          similarity: number
          text_content: string
        }[]
      }
      match_embeddings_for_subset_nodes: {
        Args: { p_query_embedding: string; p_subset_roam_uids: string[] }
        Returns: {
          content_id: number
          roam_uid: string
          similarity: number
          text_content: string
        }[]
      }
      my_accessible_resources: {
        Args: never
        Returns: Database["public"]["CompositeTypes"]["accessible_resource"][]
        SetofOptions: {
          from: "*"
          to: "accessible_resource"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      my_permissions_in_space: {
        Args: { space_id_: number }
        Returns: Database["public"]["Enums"]["SpaceAccessPermissions"]
      }
      my_space_ids: {
        Args: {
          access_level?: Database["public"]["Enums"]["SpaceAccessPermissions"]
        }
        Returns: number[]
      }
      my_user_accounts: { Args: never; Returns: string[] }
      propose_sync_task: {
        Args: {
          s_function: string
          s_target: number
          s_worker: string
          task_interval: string
          timeout: string
        }
        Returns: string
      }
      rid_or_local_id_to_concept_db_id: {
        Args: { default_space_id: number; rid: string }
        Returns: number
      }
      rid_to_space_id_and_local_id: {
        Args: { rid: string }
        Returns: Database["public"]["CompositeTypes"]["accessible_resource"]
        SetofOptions: {
          from: "*"
          to: "accessible_resource"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      schema_of_concept:
        | {
            Args: { concept: Database["public"]["Tables"]["Concept"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.schema_of_concept(concept => Concept), public.schema_of_concept(concept => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"
            SetofOptions: {
              from: '"Concept"'
              to: "Concept"
              isOneToOne: true
              isSetofReturn: true
            }
          }
        | {
            Args: { concept: Database["public"]["Views"]["my_concepts"]["Row"] }
            Returns: {
              error: true
            } & "Could not choose the best candidate function between: public.schema_of_concept(concept => Concept), public.schema_of_concept(concept => my_concepts). Try renaming the parameters or the function itself in the database so function overloading can be resolved"
            SetofOptions: {
              from: "my_concepts"
              to: "my_concepts"
              isOneToOne: true
              isSetofReturn: true
            }
          }
      unowned_account_in_shared_space: {
        Args: { p_account_id: number }
        Returns: boolean
      }
      upsert_account_in_space: {
        Args: {
          local_account: Database["public"]["CompositeTypes"]["account_local_input"]
          space_id_: number
        }
        Returns: number
      }
      upsert_accounts_in_space: {
        Args: { accounts: Json; space_id_: number }
        Returns: number[]
      }
      upsert_concepts: {
        Args: { data: Json; v_space_id: number }
        Returns: number[]
      }
      upsert_content: {
        Args: {
          content_as_document?: boolean
          data: Json
          v_creator_id: number
          v_space_id: number
        }
        Returns: number[]
      }
      upsert_content_embedding: {
        Args: { content_id: number; embedding_array: number[]; model: string }
        Returns: undefined
      }
      upsert_documents: {
        Args: { data: Json; v_space_id: number }
        Returns: number[]
      }
    }
    Enums: {
      AgentIdentifierType: "email" | "orcid"
      AgentType: "person" | "organization" | "automated_agent" | "anonymous"
      ContentVariant:
        | "direct"
        | "direct_and_children"
        | "direct_and_description"
        | "full"
      EmbeddingName:
        | "openai_text_embedding_ada2_1536"
        | "openai_text_embedding_3_small_512"
        | "openai_text_embedding_3_small_1536"
        | "openai_text_embedding_3_large_256"
        | "openai_text_embedding_3_large_1024"
        | "openai_text_embedding_3_large_3072"
      EntityType:
        | "Platform"
        | "Space"
        | "PlatformAccount"
        | "Person"
        | "AutomatedAgent"
        | "Document"
        | "Content"
        | "Concept"
        | "ConceptSchema"
        | "ContentLink"
        | "Occurrence"
      EpistemicStatus:
        | "certainly_not"
        | "strong_evidence_against"
        | "could_be_false"
        | "unknown"
        | "uncertain"
        | "contentious"
        | "could_be_true"
        | "strong_evidence_for"
        | "certain"
      Platform: "Roam" | "Obsidian"
      Scale:
        | "document"
        | "post"
        | "chunk_unit"
        | "section"
        | "block"
        | "field"
        | "paragraph"
        | "quote"
        | "sentence"
        | "phrase"
      SpaceAccessPermissions: "partial" | "reader" | "editor"
      task_status: "active" | "timeout" | "complete" | "failed"
    }
    CompositeTypes: {
      accessible_resource: {
        space_id: number | null
        source_local_id: string | null
      }
      account_local_input: {
        name: string | null
        account_local_id: string | null
        email: string | null
        email_trusted: boolean | null
        space_editor: boolean | null
        permissions:
          | Database["public"]["Enums"]["SpaceAccessPermissions"]
          | null
      }
      concept_local_input: {
        epistemic_status: Database["public"]["Enums"]["EpistemicStatus"] | null
        name: string | null
        description: string | null
        author_id: number | null
        created: string | null
        last_modified: string | null
        space_id: number | null
        schema_id: number | null
        literal_content: Json | null
        is_schema: boolean | null
        represented_by_id: number | null
        reference_content: Json | null
        author_local_id: string | null
        represented_by_local_id: string | null
        schema_represented_by_local_id: string | null
        space_url: string | null
        local_reference_content: Json | null
        source_local_id: string | null
      }
      content_local_input: {
        document_id: number | null
        source_local_id: string | null
        author_id: number | null
        creator_id: number | null
        created: string | null
        text: string | null
        metadata: Json | null
        scale: Database["public"]["Enums"]["Scale"] | null
        space_id: number | null
        last_modified: string | null
        part_of_id: number | null
        document_local_id: string | null
        creator_local_id: string | null
        author_local_id: string | null
        part_of_local_id: string | null
        space_url: string | null
        document_inline:
          | Database["public"]["CompositeTypes"]["document_local_input"]
          | null
        author_inline:
          | Database["public"]["CompositeTypes"]["account_local_input"]
          | null
        creator_inline:
          | Database["public"]["CompositeTypes"]["account_local_input"]
          | null
        embedding_inline:
          | Database["public"]["CompositeTypes"]["inline_embedding_input"]
          | null
        variant: Database["public"]["Enums"]["ContentVariant"] | null
      }
      document_local_input: {
        space_id: number | null
        source_local_id: string | null
        url: string | null
        created: string | null
        metadata: Json | null
        last_modified: string | null
        author_id: number | null
        contents: unknown
        author_local_id: string | null
        space_url: string | null
        author_inline:
          | Database["public"]["CompositeTypes"]["account_local_input"]
          | null
      }
      group_member_info: {
        id: number | null
        name: string | null
        platform: Database["public"]["Enums"]["Platform"] | null
        agent_type: Database["public"]["Enums"]["AgentType"] | null
        admin: boolean | null
      }
      inline_embedding_input: {
        model: string | null
        vector: number[] | null
      }
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      AgentIdentifierType: ["email", "orcid"],
      AgentType: ["person", "organization", "automated_agent", "anonymous"],
      ContentVariant: [
        "direct",
        "direct_and_children",
        "direct_and_description",
        "full",
      ],
      EmbeddingName: [
        "openai_text_embedding_ada2_1536",
        "openai_text_embedding_3_small_512",
        "openai_text_embedding_3_small_1536",
        "openai_text_embedding_3_large_256",
        "openai_text_embedding_3_large_1024",
        "openai_text_embedding_3_large_3072",
      ],
      EntityType: [
        "Platform",
        "Space",
        "PlatformAccount",
        "Person",
        "AutomatedAgent",
        "Document",
        "Content",
        "Concept",
        "ConceptSchema",
        "ContentLink",
        "Occurrence",
      ],
      EpistemicStatus: [
        "certainly_not",
        "strong_evidence_against",
        "could_be_false",
        "unknown",
        "uncertain",
        "contentious",
        "could_be_true",
        "strong_evidence_for",
        "certain",
      ],
      Platform: ["Roam", "Obsidian"],
      Scale: [
        "document",
        "post",
        "chunk_unit",
        "section",
        "block",
        "field",
        "paragraph",
        "quote",
        "sentence",
        "phrase",
      ],
      SpaceAccessPermissions: ["partial", "reader", "editor"],
      task_status: ["active", "timeout", "complete", "failed"],
    },
  },
} as const

